### PR TITLE
[Don't Merge]Update sphinx config for ch.bfe.sachplan-geologie-tiefenlager

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by Sgachet** [comment]
@ltclm , it's ready to review. But please **don't merge** for the moment. I wait the feedback of ambrogio and the datenherr

**Comment by ltclm** [comment]
changes have been applied on sphinx-dev trunk.

**Comment by ltclm** [comment]
oups

**Comment by ltclm** [comment]
reverted, but still visible on dev, for feedback...

**Pull request merged**
