### PR TITLE
replace swissnames3d haltestellen with bav haltestellen

### PR DESCRIPTION
**Pull request by ltclm**
the new haltestellen index is currently available on dev
dave will ask the data owner for the translation of the new categories. For now we will keep them in german.

### CODE REVIEW

**Comment by loicgasser** [comment]
For next deploy? We should probably try it out first, I propose we deal with it after tomorrow's deploy.

**Comment by ltclm** [comment]
yes, you can test on dev environment.

**Comment by ltclm** [comment]
But its probably a good idea to test it first a little bit.

**Comment by davidoesch** [comment]
+1 for testing first, not need for the next deploy
@ltclm 
translation from the offical Fahrplanbuch
DE FR IT EN RM 
Zug Train Treno Train Tren
Autobus  Carpostal Autopostale Postbus  Autobus
Schiff Bateau Battello Boat Nav
Dampfschiff Bateau à vapeur Battello a vapore Steamer nav a vapur 
Standseilbahn Funiculaire Funicolare Funicular Funiculara
Luftseilbahn Téléphérique Funivia Cableway Pendiculara 
Gondelbahn Télécabine Cabinovia Gondola-lift telecabina 
Sesselbahn Télésiège Seggiovia Chair-lift Sutgera

**Comment by ltclm** [comment]
thanks for the translation @davidoesch 
the complete list to translate is:
```
"Bedienpunkt Zug"
"Haltestelle Bus"
"Haltestelle Lift"
"Haltestelle Luftseilbahn"
"Haltestelle Luftseilbahn_Zug"
"Haltestelle Metro"
"Haltestelle Schiff"
"Haltestelle Schiff_Zahnradbahn"
"Haltestelle Standseilbahn"
"Haltestelle Standseilbahn_Bus"
"Haltestelle Standseilbahn_Luftseilbahn"
"Haltestelle Standseilbahn_Zug"
"Haltestelle Tram"
"Haltestelle_und_Bedienpunkt Zug"
"Haltestelle Zahnradbahn"
"Haltestelle Zug"
"Haltestelle Zug_Tram"
"reiner_Betriebspunkt Zug"
```

**Comment by davidoesch** [comment]
https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_en.png
https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_de.png
https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_fr.png
https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_it.png

**Comment by davidoesch** [comment]
@mariokeusen 
- We need a translation for the Features in ch.bav.haltestellen-oev
They are not the DIF, -> can you ask BAV to complete the DIF ? then we can also fix the legends translation as in https://api3.geo.admin.ch/static/images/legends/ch.bav.haltestellen-oev_de.png etc

features: 
"Bedienpunkt Zug"
"Haltestelle Bus"
"Haltestelle Lift"
"Haltestelle Luftseilbahn"
"Haltestelle Luftseilbahn_Zug"
"Haltestelle Metro"
"Haltestelle Schiff"
"Haltestelle Schiff_Zahnradbahn"
"Haltestelle Standseilbahn"
"Haltestelle Standseilbahn_Bus"
"Haltestelle Standseilbahn_Luftseilbahn"
"Haltestelle Standseilbahn_Zug"
"Haltestelle Tram"
"Haltestelle_und_Bedienpunkt Zug"
"Haltestelle Zahnradbahn"
"Haltestelle Zug"
"Haltestelle Zug_Tram"
"reiner_Betriebspunkt Zug"

**Comment by ltclm** [comment]
@loicgasser the sphinx index is on dev and ready for some tests. As discussed with @davidoesch  we dont have to wait for the translation.
[Testlink](http://mf-geoadmin3.dev.bgdi.ch)

**Comment by gjn** [comment]
@ltclm I've rebased this PR and activated in on dev. But I'm not sure about the results. For example "raron flu" has 2 results in mf-geoadmin3.dev.bgdi.ch, which I think should not be the case.

Directly on the instance, I also have 2 results:
```
1. doc_id=20420, weight=2639, feature_id=20420, detail=raron, flugplatz haltestelle bus, label=<i>Haltestelle Bus</i> <b>Raron, Flugplatz</b>, origin=gazetteer, geom_quadindex=023103133313000222022, geom_st_box2d=BOX(629766 128176,629766 128176), rank=5, x=128176.0, y=629766.0, lat=46.3043327332, lon=7.82499694824, num=1

2. doc_id=99498, weight=2629, feature_id={AC8CB94E-CC65-4692-A0AB-DF77FCDA62F3}, detail=raron, flugplatz, label=<i>Haltestelle Bus</i> <b>Raron, Flugplatz</b> (VS) - Raron, origin=gazetteer, geom_quadindex=023103133312133101111, geom_st_box2d=BOX(629758.120397663 128114.80267324,629758.120397663 128114.80267324), rank=5, x=128114.804688, y=629758.125, lat=46.3037834167, lon=7.82489061356, num=1
```
Query used: `python test.py -i swisssearch_preview -e "*raron* *flu*"`

**Comment by gjn** [comment]
@davidoesch @cedricmoullet Could you please validate search results on [dev](https://mf-geoadmin3.dev.bgdi.ch)

**Comment by ltclm** [comment]
category translation will be activated with: https://github.com/geoadmin/mf-chsdi3/pull/1744

**Comment by ltclm** [comment]
@gjn the first result comes from bav-haltestellen
the second result still comes from swissnames3d, to get rid of this result we have to rebuild the index swissnames3d, swissinames3d_metaphone and swissnames3d_soundex.
I have just rebuilt the swissnames indices.

**Comment by gjn** [comment]
Understood.

We need to keep this in minde for the deploy. Please note it in the doc on what needs to be done for the sphinx deploy.

**Comment by davidoesch** [comment]
a nice to have to get "showTooltip=true" on click ;.-)

**Comment by gjn** [comment]
@ltclm I've rebased again to master.

**Comment by cedricmoullet** [comment]
Seems good to me

2015-12-03 20:04 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> @ltclm <https://github.com/ltclm> I've rebased again to master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/service-sphinxsearch/pull/245#issuecomment-161748805>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
@davidoesch Can we activate this?

**Comment by davidoesch** [comment]
Activate

**Pull request merged**
