### PR TITLE
BGDIDIC-2494: add ch_bafu_gewaesser_uferbestockung

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — CHANGES_REQUESTED** [review]
the query is not working:
```SQL
ERROR:  column "zone" does not exist
LINE 11:             , zone::text as feature_id  
                       ^
SQL state: 42703
Character: 572
```
please check the queries before assigning the pr.

**Comment by rebert** [comment]
Dito

**Comment by rebert** [comment]
```ERROR:  column "zone" does not exist
LINE 1: ...transform(the_geom, 2056)) as geom_st_box2d_lv95, zone::text...
                                                             ^
SQL state: 42703
Character: 426```

**Comment by faselm** [comment]
It should be OK now. How o test? In the wiki it is written: Regrettably sphinx indexes can not be tested before the feature branch has been merged into the milestone branch

**Review by ltclm — APPROVED** [review]
ok now, thank you!

you can copy the sql statement and run it with pgadmin or psql. you can add limit 1 to the end of the query to avoid too much data transfer...

**Comment by faselm** [comment]
OK, thanks!

**Pull request merged**
