### PR TITLE
do a graceful explain verbose on all queries matching the database

### PR DESCRIPTION
**Pull request by ltclm**
pattern
on error the scan continues

### CODE REVIEW

**Comment by loicgasser** [comment]
LGTM
As I said if we deploy a table and sphinx indices are wrong shall we stop it or not?
That's what
https://github.com/geoadmin/service-sphinxsearch/pull/300
achieves

If you want to never fail we take this one otherwise we take 300.
I'll let you decide.

**Comment by loicgasser** [comment]
Related sphinx indices

**Comment by ltclm** [comment]
the trigger should continue in my opinion, if you agree we can take this solution.

**Comment by loicgasser** [comment]
+1 let s mitigate.

**Comment by gjn** [comment]
Any way to run this in jenkis on PR's?

Or to run it before deploying new sphinx config?

**Pull request merged**
