### PR TITLE
remove txt and py files on target if they dont exist on the source

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
see mail from @ponceta Donnerstag, 5. Februar 2015 11:36

**Comment by gjn** [comment]
@ponceta @ltclm  hmm. Not sure about this as I don't know rsync enough. doesn't this delete all indices from data directory (because they are not present in CODE_DIR?)

I would rather delete those files by hand once and be done with it, no?

**Comment by ltclm** [comment]
thanks for the advice @gjn 
the rsync was indeed deleting all the indices.
The missing ``exclude="*"`` will make the rsync delete only txt and py files in the target directory which are not present in the code dir.

**Comment by gjn** [comment]
Please merge if tested :)

**Comment by ltclm** [comment]
The rsync is working fine, but you have to delete (manually) the old wordforms files first on the deploy source (/var/lib/sphinxsearch/data/index/)

**Pull request merged**
