### PR TITLE
BGDIDIC-2472: Add zone_name_de

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Comment by ltshb** [comment]
@faselm  @ltclm  should not this be on the milestone branch ?

**Comment by ltclm** [comment]
@faselm if this is for the next deploy '2022-09-07' please change the target to `develop-2022-09-07`

**Comment by rebert** [comment]
@faselm what is the status of this PR. Do you want to make this PR against the milestone branch? develop-2022-09-07?

**Comment by rebert** [comment]
@b4l didn't you continue with this layer? maybe you know what should happen with this PR

**Comment by faselm** [comment]
This pr should be ready for the deploy when it has been approved. b4l worked on this layer during my holiday so probably he knows if the other things are ready as well

**Review by rebert — APPROVED** [review]
lgtm

**Comment by b4l** [comment]
@rebert this has been pushed to the next deploy in November. I was not aware of this PR, sorry!

**Pull request merged**
