### PR TITLE
Add sphinx config for bafu layer (ch.bafu.hydrologie-q347,ch.bafu.was…

### PR DESCRIPTION
**Pull request by alcapat**
…serbau-vermessungsstrecken, ch.bafu.hydrologie-niedrigwasserstatistik, ch.bafu.typisierung-fliessgewaesser)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@ltclm Could you please review and merge if ok ?

**Comment by ltclm** [comment]
please resolve the conflicts @alcapat

**Comment by alcapat** [comment]
@ltclm conflicts are resolved. bgdi_id attribute was removed and coalesce function was added

**Comment by ltclm** [comment]
thanks!

**Pull request merged**
