### PR TITLE
Communes gazetter

### PR DESCRIPTION
**Pull request by loicgasser**
[TEST](https://mf-geoadmin3.dev.bgdi.ch/)

thanks @ltclm for the regexp

**This PR adds the commune name to the search field.**

@davidoesch Let me know if you're happy with the ranking.

I'm trying to search for the following location:

Hauptgipfel Stelli (GR) - Arosa

While this works on https://map.geo.admin.ch with the search term "stelli", I couldn't get it working with the SearchServer REST API:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&amp;lang=de&amp;returnGeometry=true&amp;origins=gazetteer&amp;searchText=stelli

First of all, it only returns 30 results despite the (default) limit of 50.

Additionally, the result set never contains "Hauptgipfel Stelli (GR) - Arosa". Maybe someone has an idea how the search has to look like to get the desired result?

I was also wondering how to submit multiple search terms (the doc is saying up to 10 terms). What I tried is this:
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&amp;lang=de&amp;returnGeometry=true&amp;origins=gazetteer&amp;searchText=stelli+arosa

but only an empty result set is returned:
{
•	"fuzzy": "true",
•	"results": [ ]
}

If someone could shed some light on how to make searching for multiple search terms work, that would be great.

### CODE REVIEW

**Comment by loicgasser** [comment]
Rotation of indices not ready yet, please wait another 5-10min before testing.

**Comment by davidoesch** [comment]
@loicgasser can you provide a testlink to the service and post the *result* of the query into https://groups.google.com/forum/#!topic/geoadmin-api/V_LHTziW3oA so the customer can give feedback to it?

**Comment by loicgasser** [comment]
[Test Link](https://mf-chsdi3.dev.bgdi.ch/shorten/714d7a2dcb)

**Comment by davidoesch** [comment]
@loicgasser what is the dev link to your branch for makeing this call?
https://api3.geo.admin.ch/rest/services/api/SearchServer?type=locations&amp;lang=de&amp;returnGeometry=true&amp;origins=gazetteer&amp;searchText=stelli

**Comment by loicgasser** [comment]
It's in dev in general. We only have one source of indices. Not a branch. We changed the detail field in the indices. The detail field represents the text field we query when performing a search request.
CHSDI controller hasn't changed.

**Comment by loicgasser** [comment]
@syabru it is exactly the same service behind the scene. The dev API link points to these new indices. (until they get overriden)
[Test Link](https://mf-chsdi3.dev.bgdi.ch/rest/services/api/SearchServer?type=locations&amp;lang=de&amp;returnGeometry=true&amp;origins=gazetteer&amp;searchText=stelli%20arosa)
Please don't use dev links in prod, only for testing purposes.

**Comment by syabru** [comment]
Thanks @loicgasser! It works as expected.

**Pull request merged**
