### PR TITLE
BGDIDIC-2583: add from/to node uuid

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — CHANGES_REQUESTED** [review]
tests are failing
```


ERROR: wrong query detected in database: EXPLAIN VERBOSE SELECT bgdi_id as id             , uuid as label             , 'feature' as origin             , remove_accents(concat_ws(' ', uuid, from_node_uuid, to_node_uuid)) as detail             , 'ch.swisstopo.swisstne-base' as layer             , quadindex(the_geom) as geom_quadindex             , st_y(st_transform(st_centroid(the_geom),4326)) as lat             , st_x(st_transform(st_centroid(the_geom),4326)) as lon             , box2d(st_transform(the_geom, 21781)) as geom_st_box2d             , box2d(st_transform(the_geom, 2056)) as geom_st_box2d_lv95             , uuid as feature_id         from tlm.swisstne_base_sphinx
--
154 | query:
155 | EXPLAIN VERBOSE SELECT bgdi_id as id             , uuid as label             , 'feature' as origin             , remove_accents(concat_ws(' ', uuid, from_node_uuid, to_node_uuid)) as detail             , 'ch.swisstopo.swisstne-base' as layer             , quadindex(the_geom) as geom_quadindex             , st_y(st_transform(st_centroid(the_geom),4326)) as lat             , st_x(st_transform(st_centroid(the_geom),4326)) as lon             , box2d(st_transform(the_geom, 21781)) as geom_st_box2d             , box2d(st_transform(the_geom, 2056)) as geom_st_box2d_lv95             , uuid as feature_id         from tlm.swisstne_base_sphinx
156 | error:
157 | column "from_node_uuid" does not exist
158 | LINE 1: ...            , remove_accents(concat_ws(' ', uuid, from_node_...

```

you can test the queries locally, before pushing and creating a pr with
```bash
make check-config-local
```

or check the codebuild output in the swisstopo-bgdi-builder account. You should have access to it.

**Comment by ltclm** [comment]
@faselm you cannot merge prs with queries that are not working, which is good.
merges into develop-xxx branch are automatically deployed to dev and used for index creation. This wont work if the databases on dev staging are not up-to-date.
you have to
* fix the database, add the columns
* re-push the commit in this branch to trigger  a codebuild run

**Comment by faselm** [comment]
Still have to recreate the view for this one..

**Comment by faselm** [comment]
@ltclm This one should be good to merge now

**Review by ltclm — APPROVED** [review]

**Pull request merged**
