### PR TITLE
Remove queryable layers

### PR DESCRIPTION
**Pull request by gjn**
Once https://github.com/geoadmin/mf-geoadmin3/pull/1982 is merged and deployed to prod, we don't need
queryable layers in sphinx anymore. We can adapt the data-integration process.

This PR is in preparation to this. Not tested. Do not merge.

### CODE REVIEW

**Comment by gjn** [comment]
I'll update this to remove all queryable indices.

**Comment by gjn** [comment]
@ltclm Try to review, merge and deploy this today?

**Comment by ltclm** [comment]
i like this pr!! The number of sphinx indexes is reduced from 285 -> 90 :+1: 
Everything is working fine (chsdi functional nosetests and some manual tests).

**Comment by ponceta** [comment]
Nice!

**Pull request merged**
