### PR TITLE
Add shop sphinxsearch

### PR DESCRIPTION
**Pull request by daguer**

### CODE REVIEW

**Comment by loicgasser** [comment]
LGTM
I'll merge once https://github.com/geoadmin/mf-chsdi3/pull/2313 is adapted.

**Comment by loicgasser** [comment]
Now if you could prepare the delete PR post-deploy please?

**Comment by daguer** [comment]
Can you give me the link to the wiki with the list to do?
Thanks

2016-11-04 14:39 GMT+01:00 Gasser Loïc <notifications@github.com>:

**Comment by loicgasser** [comment]
Sure you can follow this template. It's maybe best if you open an issue and check things as you do them.

https://github.com/geoadmin/mf-chsdi3/issues/2274

**Pull request merged**
