### PR TITLE
replace datasource for swisssearch parcel search with mogis data

### PR DESCRIPTION
**Pull request by ltclm**
use the mogis datasource for parcel search.
We can drop the scheme dritte_master.kantone after the merge and deploy of this pr.
the new index is on sphinx_dev

### CODE REVIEW

**Comment by cedricmoullet** [comment]
What will be the update rate with this PR ?

**Comment by ltclm** [comment]
@ltgap can you tell us about the planned update rate for geoshop->mogis->gdwh?

**Comment by ltgap** [comment]
The GIS Users alone would probably already be happy with 1 month, but if the MOgis data are needed elsewhere in our universe with a higher update rate, we can adapt. The processing of the Geoshop-Interlis Data @stflustop is the key factor here.

**Comment by davidoesch** [comment]
The update rate needs to be in sync with the update rate of cadastral-webmap https://jira.swisstopo.ch/browse/BGDIDI_KB-741

**Comment by ltclm** [comment]
yes @davidoesch the current situation is not in sync, geoshop csv export (swisssearch) is weekly, mogis import is every 3 months.
actually you can choose between 
* out of sync situation, current (swisssearch weekly, identify quarterly)
* in sync situation swisssearch and identify quarterly

**Comment by davidoesch** [comment]
Then out of sync is the choice. An ETA when this will be fixed?

**Comment by cedricmoullet** [comment]
with that, we solve nothing.... we need to have a weekly update for all.

**Comment by loicgasser** [comment]
@ltclm is this ever gona be merged? otherwise let's close

**Comment by ltgap** [comment]
@eraymann is on the verge of a breakthrough for automatic updates (even daily?)

**Pull request closed without merging**
