### PR TITLE
BGDIDIC-1503: add poly index

### PR DESCRIPTION
**Pull request by faselm**

### CODE REVIEW

**Review by ltclm — COMMENTED** [review]
is this working as expected? i think it would make more sense to union the two requests or create a view for the sphinx index.

**Review by ltclm — CHANGES_REQUESTED** [review]
looks better now, thank you @faselm 
just make sure that the bgdi_id of the two unioned tables / queries is unique.
you can fix the ci issue by granting www-data read permissions to the view
`permission denied for view view_tiefengeothermie_projekte_union`

**Comment by faselm** [comment]
OK, I granted the permissions. I get an error with `make pg2sphinx` btw when I want to test an index:

```
(service-sphinxsearch-PpWyiGmV) mfasel@mfasel:~/service-sphinxsearch$ STAGING=dev INDEX=ch_swisstopo_geologie_tiefengeothermie_projekte make pg2sphinx
make[1]: Entering directory '/home/mfasel/service-sphinxsearch'
 - load env file dev.env
create folder /var/local/efs-dev/geodata/service-sphinxsearch/dev/index/ if it does not yet exist
mkdir -p /var/local/efs-dev/geodata/service-sphinxsearch/dev/index/
./scripts/pg2sphinx.sh
make[2]: Entering directory '/home/mfasel/service-sphinxsearch'
aws --profile swisstopo-bgdi-builder ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 974517877189.dkr.ecr.eu-central-1.amazonaws.com 2> /dev/null

The config profile (swisstopo-bgdi-builder) could not be found
make[2]: *** [Makefile:249: dockerlogin] Error 1
make[2]: Leaving directory '/home/mfasel/service-sphinxsearch'
make[1]: *** [Makefile:220: pg2sphinx] Error 2
make[1]: Leaving directory '/home/mfasel/service-sphinxsearch'
```
I dod a make setup, make dev, make ci but no changes..

**Comment by ltclm** [comment]
you have to provide your aws credentials on this machine `/home/mfasel/.aws/config` or `/home/mfasel/.aws/credentials`

**Comment by ltclm** [comment]
and/or you can manually restart the codebuild job in the aws console
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/974517877189/projects/service-sphinxsearch/build/service-sphinxsearch%3Aca6afa1a-3be2-4c41-b5b2-c2773b918040?region=eu-central-1

**Comment by ltclm** [comment]
or you change the commit hash of the latest commit with `git commit --amend --no-edit` and push force this to trigger a new codebuild run.

**Comment by faselm** [comment]
OK, thanks. Where can I get the aws creditentials? I don't have it I think.

**Comment by faselm** [comment]
How can I test if the index is working before merging the pr too? after make dockerrun?

**Comment by ltclm** [comment]
you can test it on your local instance with `make check-config-local`

**Comment by faselm** [comment]
I get a error "no space left":
```
sha256:ed57bf9ec6a9d9be9fc9a21265a7f5c84f66e11606bd043447bcd4937a62916d
 - load env file dev.env
cat conf/*.part > conf/sphinx.conf.in
cat: write error: No space left on device
make: *** [Makefile:242: config] Error 1
```

**Comment by faselm** [comment]
docker images is huge

**Comment by faselm** [comment]
OK, docker system prune -a fixed that. The test was successful. Can I merge the pr?

**Review by ltclm — APPROVED** [review]
thank you!

**Comment by faselm** [comment]
@ltclm The index doesn't seem to work for purpose_xx. Also, "Magglingen" should return two results (point and poly). Is the solution here adapted for such case when two names are the same?

**Comment by faselm** [comment]
Ah I think I remember the table should be deployed again..

**Pull request merged**
