### PR TITLE
remove debug information from swisssearch_preview swissnames3d index

### PR DESCRIPTION
**Pull request by ltclm**
Since we have lines and polygons now, we cant provide commune and canton information anymore.

### CODE REVIEW

**Comment by gjn** [comment]
As compared to sn25, are we loosing kanton and gemeindename in the label?

**Comment by ltclm** [comment]
yes, if the data owner does not provide this information as official part of the data we would have to generate this information by spatial queries within the sphinx index generation or data integration. 
But i dont like this at all for the following reasons:
* there are features outside the kantone, gemeinde perimeter, how do we treat them?
* Lines and Polygons can overlap multiple gemeinde/kantone features, how do we order them, how many elements do we list?

**Comment by gjn** [comment]
I think we have to do something.

[Old results (sn25)](https://map.geo.admin.ch/?swisssearch=gasse) looked much better (clearer label) than [new gazetteer based](https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?swisssearch=gasse) as they contained canton/gemeinde. There are many same/similar names and having the all with the same label in the result list is quite bad (when we remove the debug message it won't be better)

We can't deploy branches right now, but I let my private account up until Tuesday next week.

@davidoesch @cedricmoullet What do you think?

**Comment by davidoesch** [comment]
Agree the old ones are way better. Issue of data owner @mariokeusen we need to have an improved dataset

**Comment by ltclm** [comment]
i am currently recreating the swissnames indexes on dev.
I have added communal and cantonal information to each feature using spatial queries:
```sql
<b>'||coalesce(name,'')||'</b> ('||coalesce((select string_agg(kanton,',') from tlm.prodas_spatialseltype_kanton g where f.the_geom && g.the_geom AND st_intersects(f.the_geom,g.the_geom)),'')||') - '||coalesce((select string_agg(bez,',') from tlm.prodas_spatialseltype_gemeinde g where f.the_geom && g.the_geom AND st_intersects(f.the_geom,g.the_geom)),'') as label
```
In case of multiple intersections:
We have to define the order of the elements in the list (by distance to feature centroid?
The number of elements in the list?
Anyone a proposition?

Waiting for a new dataset can take a long time...

**Comment by davidoesch** [comment]
Order of elements :

Can you drop all available elements here as list?

**Comment by ltclm** [comment]
this would be a possible result:

<b>Lac de la Gruyère</b> (FR) - La Roche,Pont-en-Ogoz,Botterens,Broc,Corbières,Echarlens,Hauteville,Marsens,Morlon,Pont-la-Ville,Rossens (FR)

There could even be multiple cantons.

**Comment by ltclm** [comment]
<b>Bodensee</b> (SG,TG) - Rorschach,Goldach,Rorschacherberg,Steinach,Thal,Kreuzlingen,Kesswil,Romanshorn,Salmsach,Egnach,Altnau,Bottighofen,Güttingen,Horn,Arbon,Uttwil,Münsterlingen,Bodensee (SG),Bodensee (TG)

**Comment by davidoesch** [comment]
Und die Attribute dazu? ( Kanton -... Flurname.... Fluss)

**Comment by ltclm** [comment]
was für attribute?
bei sn25 haben wir neben dem sn25 eintrag den kanton und die gemeinde dargestellt. dasselbe machen wir jetzt für swissnames3d oder?

**Comment by davidoesch** [comment]
+1 for marcel: we have to create this list by our own. will take to long if
we go through topo

Steps:

A) we try to reengineer sn25 for tlm
- start with distance to feat. centroid ( marcel: can you list all possible
TLM attributes? swissnames3d point etc, so we can sort them..)
- remove multiple results
- add as well ct and city names as it is currently
- ranking order: as ist is currently ( I assume:  Ct,county, village,
roadname, ....then add the new stuff)
- challenge: the user has to be able to identify what is a POI and what is
river what is streetname. so i would really start with what we have in sn25
and then move forward with adding new tlm feature by feature - if necessary)

2015-07-03 16:42 GMT+02:00 Clausen Marcel <notifications@github.com>:

**Comment by davidoesch** [comment]
Plus: we have to let it test by Schweizmobil.ch (as we did last time)

**Comment by ltclm** [comment]
the following attributes are available for feature identification:
objektart:
```
"Haupthuegel"
"Seeinsel"
"Staudamm"
"Klosterareal"
"Rastplatzareal"
"Unterwerkareal"
"Skisprungschanze"
"Schwimmbadareal"
"Strassenpass"
"Ort"
"Huegel"
"Autofaehre"
"Oeffentliches Parkplatzareal"
"Quartier"
"Grossregion"
"Golfplatzareal"
"Quelle"
"Schmalspur"
"Heliport"
"Lokalname swisstopo"
"Strasse"
"Wehr"
"Flugfeldareal"
"Sportplatzareal"
"Pferderennbahnareal"
"Hauptgipfel"
"Massnahmenvollzugsanstaltsareal"
"Zollamt 24h"
"Sesselbahn"
"Personenfaehre ohne Seil"
"Personenfaehre mit Seil"
"Fliessgewaesser"
"Sakrales Gebaeude"
"Haltestelle Bahn"
"Normalspur"
"Ein- und Ausfahrt"
"Landesgrenzstein"
"Gebaeude Einzelhaus"
"Tal"
"Haltestelle Schiff"
"Huegelzug"
"Friedhof"
"Gletscher"
"Historisches Areal"
"Flurname swisstopo"
"Verzweigung"
"Zollamt eingeschraenkt"
"Gondelbahn"
"Truppenuebungsplatz"
"Standplatzareal"
"Messeareal"
"Grotte, Hoehle"
"Kapelle"
"Spitalareal"
"Bildstock"
"Rodelbahn"
"Turm"
"Skilift"
"Zooareal"
"Graben"
"Brunnen"
"Abwasserreinigungsareal"
"Haupttal"
"Erratischer Block"
"Massiv"
"Grat"
"Felsblock"
"Wasserfall"
"Denkmal"
"Bobbahn"
"Seeteil"
"Flugplatzareal"
"Flughafenareal"
"Campingplatzareal"
"Kehrrichtverbrennungsareal"
"Felskopf"
"Ortsteil"
"Oeffentliches Parkareal"
"Deponieareal"
"Landschaftsname"
"Schul- und Hochschulareal"
"Haltestelle Bus"
"Kraftwerkareal"
"Pass"
"See"
"Transportseil"
"Ausfahrt"
"Gebiet"
"Freizeitanlagenareal"
"Offenes Gebaeude"
"Uebrige Bahnen"
"Zollamt"
"Gipfel"
"Luftseilbahn"
"Quartierteil"
"Staumauer"
"Alpiner Gipfel"
"Kleinbahn"
"Aussichtspunkt"
"Verladestation"
```

objektklasse
```
"TLM_SPORTBAUTE_LIN"
"TLM_VERKEHRSAREAL"
"TLM_STRASSE"
"TLM_AUS_EINFAHRT"
"TLM_NUTZUNGSAREAL"
"TLM_NAME_PKT"
"TLM_STEHENDES_GEWAESSER"
"TLM_FREIZEITAREAL"
"TLM_HALTESTELLE"
"TLM_EISENBAHN"
"TLM_GEBAEUDE"
"TLM_SCHIFFFAHRT"
"TLM_UEBRIGE_BAHN"
"TLM_STRASSENINFO"
"TLM_GELAENDENAME"
"TLM_EINZELOBJEKT"
"TLM_GEBIETSNAME"
"TLM_FLIESSGEWAESSER"
"TLM_MORPH_KLEINFORM_PKT"
"TLM_FLURNAME"
"TLM_SIEDLUNGSNAME"
"TLM_STAUBAUTE"
```

These attributes are not translated. 
In a first step, i would not try to describe the feature types in the result. We should rebuild the same we had with sn25 and afterwards try to improve this.

**Comment by ltclm** [comment]
the new labelled index is working now.
Try to search for ``valle du rhone``

**Comment by ltclm** [comment]
the label is truncated to 80 chars now.
https://mf-chsdi3.dev.bgdi.ch/ltjeg/rest/services/ech/SearchServer?searchText=Berner%20Alpen444&lang=de&type=locations_preview

**Comment by gjn** [comment]
I like it. Integration can be tested [here](https://mf-geoadmin3.dev.bgdi.ch/ltjeg/)

**Comment by ltclm** [comment]
I like this one : search for ``Kurhaus Ebene``

**Pull request merged**
