### PR TITLE
Fix bodsearch

### PR DESCRIPTION
**Pull request by Sgachet**

### CODE REVIEW

**Comment by gjn** [comment]
Why was this parameter introduced in the bod?

**Comment by ltclm** [comment]
it is already handled in the view, this where condition is useless, the view only returns values with bodsearch=tru

**Comment by gjn** [comment]
@loicgasser Please close if you agree that this can be closed.

**Comment by loicgasser** [comment]
@ltclm this PR is linked to https://github.com/geoadmin/tool-wms/pull/117

So we remove it the view and add it here, because these views are used in CHSDI to build html popups and legends.

I don't think it is correct to assume that if bodsearch is False we don't have html popups and legends.

Would it cause any side effect? I don't think so.

**Comment by gjn** [comment]
Interface A): give me objects that are searchable
Interface B): give me all objects and I look for myself which are searchable.

In other words: where to put the businesslogic?

The more clients of interfaces you have, the more the business logic should be in the implementation of the interface - and not in the interface (and carried to clients).

**Comment by loicgasser** [comment]
> In other words: where to put the businesslogic?

Certainly not in a view that represents the metadata of `all` the layers.
Please trust me on this one.

**Comment by ltclm** [comment]
our wiki knows 
https://ltwiki.adr.admin.ch:8443/display/BGDI/16+-+BOD+tables

bodsearch | boolean default false | defines wheter a layer is published in the chsdi services using the views bod.re3.view_bod_layer_info_en like legend, htmlpopup, identify etc. | important! If bodsearch = false the layer is invisible for re3 services. This is wanted that way for baselayers. | x | x | iwi
-- | -- | -- | -- | -- | -- | --

Some time ago we had several attributes (queryable, searchable, ...). 
> Searchable -> you can search features
Queryable -> you can perform geometric operations
Bodsearch -> you can search for the layer metadata


we decided to replace this attribute with one atttribute called ``bodsearch``. the attribute enables **all or nothing** (as it is documented in the wiki). layers with bodsearch = False are not supposed to be visible in any interface, that's why i think it is correct like this. The view is not showing all layers, it shows only the layers which are re3/service enabled. 
We should verify the column bodsearch for all layers, originally only the baselayers had ``bodsearch=FALSE``, for all other layers this should be TRUE in my eyes.

**Comment by AFoletti** [comment]
> We should verify the column bodsearch for all layers, originally only the baselayers had bodsearch=FALSE, for all other layers this should be TRUE in my eyes.
☝️ 
+1 for that!

**Comment by loicgasser** [comment]
Here is a list of layers that have BOD search set to false.

```
"ch.astra.projektierungszonen-nationalstrassen.oereb"
"ch.bav.baulinien-eisenbahnanlagen.oereb"
"ch.bav.kataster-belasteter-standorte-oev.oereb"
"ch.bav.projektierungszonen-eisenbahnanlagen.oereb"
"ch.bazl.baulinien-flughafenanlagen.oereb"
"ch.bazl.kataster-belasteter-standorte-zivilflugplaetze.oereb"
"ch.bazl.projektierungszonen-flughafenanlagen.oereb"
"ch.bazl.sicherheitszonenplan.oereb"
"ch.bfs.arealstatistik-bodennutzung-04"
"ch.bfs.arealstatistik-bodennutzung-10"
"ch.bfs.arealstatistik-bodennutzung-1985-04"
"ch.bfs.arealstatistik-bodennutzung-1985-10"
"ch.bfs.arealstatistik-bodennutzung-1985-punkte"
"ch.bfs.arealstatistik-bodennutzung-1997-04"
"ch.bfs.arealstatistik-bodennutzung-1997-10"
"ch.bfs.arealstatistik-bodennutzung-1997-punkte"
"ch.bfs.arealstatistik-bodennutzung-punkte"
"ch.blw.ursprungsbezeichnungen-fleisch-ap_wurst"
"ch.swisstopo.geologie-geologische_einheiten-onegeology"
"ch.swisstopo.geologie-geologische_einheiten-onegeologyeurope"
"ch.swisstopo.geologie-tektonische_einheiten-onegeology"
"ch.swisstopo.geologie-tektonische_stoerungen-onegeology"
"ch.swisstopo.geologie-tektonische_stoerungen-onegeologyeurope"
"ch.swisstopo.images-spotimage"
"ch.swisstopo.pixelkarte-farbe"
"ch.swisstopo.pixelkarte-grau"
"ch.swisstopo.swissimage"
"ch.swisstopo.swisstlm3d-karte-farbe.3d"
"ch.swisstopo.swisstlm3d-karte-grau.3d"
"ch.vbs.armeelogistik-logistikraeume"
```

**Comment by gjn** [comment]
So what do we do?

**Comment by ltclm** [comment]
Happy first birthday :tada:

**Comment by pakb** [comment]
ping @Sgachet @ltclm @rebert 
What do we do with this?

**Pull request closed without merging**
